export const tradingTypes = ['Hotels & Resorts',
    'Restaurants & Cafes',
    'Catering Services',
    'Food Trucks & Street Food Vendors',
    'Bed & Breakfast Guest Houses',
    'Event Catering & Management',
    'Fast Food Chains',
    'Specialty Food Stores',
    'Crop Farming',
    'Livestock Farming',
    'Timber Harvesting',
    'Aquaculture',
    'Forestry Management',
    'Fishing & Seafood Processing',
    'Organic Farming',
    'Agricultural Equipment Sales & Services',
    'Supermarkets & Grocery Stores',
    'Clothing Retailers',
    'Electronics Retailers',
    'Online Retailers',
    'Wholesale Distributors',
    'Specialty Retail Stores',
    'Department Stores',
    'E-commerce Platforms',
    'Residential Construction',
    'Commercial Construction',
    'Renovation Services',
    'Civil Engineering',
    'Architectural Services',
    'Building Materials Suppliers',
    'Interior Design Services',
    'Landscaping & Outdoor Construction',
    'Schools & Universities',
    'Online Education Platforms',
    'Tutoring Services',
    'Educational Supplies Stores',
    'Language Schools',
    'Vocational Training Centers',
    'Educational Technology Providers',
    'Educational Consultancies',
    'Banks & Credit Unions',
    'Insurance Companies',
    'Investment & Financial Advisory Firms',
    'Payment (mobile-money) Services Providers',
    'Mortgage Lenders',
    'Accounting Services',
    'Tax Preparation Services',
    'Wealth Management Services',
    'Hospitals & Clinics',
    'Pharmacies',
    'Medical Laboratories',
    'Dental Clinics',
    'Mental Health Services',
    'Home Healthcare Services',
    'Medical Equipment Suppliers',
    'Alternative Medicine Providers',
    'Software Development',
    'Telecommunications Services',
    'Internet Service Providers',
    'Media & Broadcasting',
    'Data Analytics Companies',
    'IT Consulting Services',
    'Social Media Platforms',
    'Cybersecurity Firms',
    'Automotive Manufacturing',
    'Electronics Manufacturing',
    'Textile & Apparel Production',
    'Food Processing Plants',
    'Pharmaceutical Manufacturing',
    'Furniture Production',
    'Aerospace Manufacturing',
    'Chemical Production',
    'Coal Mining',
    'Metal Ore Mining',
    'Stone Quarrying',
    'Oil & Gas Extraction',
    'Mineral Exploration',
    'Diamond Mining',
    'Sand & Gravel Extraction',
    'Salt Mining',
    'Government Agencies',
    'Military Services',
    'Border Control Services',
    'Public Works Departments',
    'Regulatory Bodies',
    'Legal Services',
    'Consulting Firms',
    'Marketing Agencies',
    'Engineering Services',
    'Architecture Firms',
    'Human Resources Consultancies',
    'Event Planning Services',
    'Translation Services',
    'Real Estate Agencies',
    'Property Management Companies',
    'Real Estate Developers',
    'Rental Agencies',
    'Home Staging Services',
    'Real Estate Investment Firms',
    'Land Surveyors',
    'Title Insurance Companies',
    'Freight Transportation',
    'Logistics Companies',
    'Shipping & Maritime Services',
    'Warehousing & Distribution',
    'Moving & Storage Services',
    'Courier & Delivery Services',
    'Public Transportation',
    'Vehicle Rental Services',
    'Electricity Providers',
    'Gas Distribution Companies',
    'Water Treatment Plants',
    'Renewable Energy Providers',
    'Utility Infrastructure Maintenance',
    'Waste Management Services',
    'Sewage Treatment Facilities',
    'Irrigation Systems Providers',
    'Sports Clubs & Stadiums',
    'Event Planning Services',
    'Indoor Playgrounds',
    'Gaming & Casinos',
    'Night Clubs & Bars',
    'Spas & Wellness Centres',
    'Gym & Fitness Centres',
    'Salons & Barber Shops'];
